apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-service.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "notification-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
